### ISSUE TITLE
Request: Add example for conferences

### ISSUE THREAD

**Issue by joshkpeterson** [nexmo-community/nexmo-node-quickstart#9]
There are currently examples at https://docs.nexmo.com/voice/voice-api/conversation in python / ruby / php, but I could personally use a node example.

If anyone has something that's not polished and ready just laying around, I'd totally love to see it in a gist or whatever.

Otherwise I may just go through the python example piece by piece and try to replicate. If I do that successfully maybe I'll make a pull request. Thanks!

**Comment by leggetter** [comment]
@joshkpeterson - sorry for the delay. https://github.com/nexmo-community/nexmo-node-quickstart/pull/11 provides an example.

**Comment by lornajane** [comment]
Example already added, closing this issue
